### ISSUE TITLE
After installing the package (executing the composer require lintaba/orchid-tables command), errors appeared in the console

### ISSUE THREAD

**Issue by EduardRe** [lintaba/orchid-tables#4]
### Steps to Reproduce the Problem

  1. installing the package executing the composer require lintaba/orchid-tables command, errors appeared in the console
  2. And now I can't execute any command in the console, even php artisan -v

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/65927124/164995963-b48e7f6f-084f-490b-8ea3-87eb1f5d82e3.png)

### Specifications

  - ORCHID Platform Version: 12.3.0
  - Laravel Version: 9.8.1
  - PHP Version: 8.1
  - Database Version: 8.0.27

### Other Notes
It's a very strange situation, composer itself is also the latest version, I always update everything. Help solve the problem.

**Comment by lintaba** [comment]
its probably came from an orchid platform upgrade that wasnt handled properly in this repository:

https://github.com/lintaba/orchid-tables/blob/333ea7e31d5da6baf1c7834b18488fbe35a909a3/src/OrchidTablesServiceProvider.php#L85
vs
https://github.com/orchidsoftware/platform/blob/master/src/Platform/Providers/PlatformServiceProvider.php#L36

I can take a look at it in a few days, but feel free to send a PR.

**Comment by EduardRe** [comment]
I tried to correct it, but it didn't work out. There are always some mistakes. Class "Lintaba\OrchidTables\OrchidTablesServiceProvider" not found
Either I'm doing something wrong, or that's not the only problem, please take a look. I'm in no hurry

**Comment by lintaba** [comment]
Published a new version (1.0.4) that restores the dependency requirement (now stays with orchid 10)

Problem is, orchid removed the `addPublicDirectory` with 11.0 (https://github.com/orchidsoftware/platform/issues/1965).

Also created a new release (1.1.0) that fixes this issue, and adds support for orchid 12.

**Comment by EduardRe** [comment]
Hello, thank you so much for fixing the problem, yes, there is no error now, but now after installing such an error in the admin panel, how can I fix it?
![image](https://user-images.githubusercontent.com/65927124/165272403-06786c2c-6065-4fcf-af04-d84849551c04.png)

**Comment by lintaba** [comment]
please check if `vendor/lintaba/orchid-tables/src/OrchidTablesServiceProvider.php` file is present.
something may went wrong with install. Can you do a `composer update`, and check its output?
if it doesnt resolve, please try to remove your `vendor` directory, and run `composer install` again.

**Comment by EduardRe** [comment]
Thank you very much, it worked, for some reason some files did not fly to the server. Now everything is fine, I will try to use new tables.
